//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerSupplier
    {
        public int CSID { get; set; }
        [DisplayName("Customer Supplier Name")]
        [Required(ErrorMessage = "Customer Supplier Name is required")]
        public string CSName { get; set; }
        [DisplayName("Address")]
        [Required(ErrorMessage = "Address is required")]
        public string CSAddress { get; set; }
        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Phone Number is required")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string PhoneNo { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Email is invalid")]
        public string Emailad { get; set; }
        [DisplayName("Payment ID")]
        [Required(ErrorMessage = "Payment ID is required")]
        public Nullable<int> PaymentID { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
