//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Stock
    {
        public int StockID { get; set; }
        [DisplayName("Product Availability")]
        [Required(ErrorMessage = "Product Availability is required")]
        public string Availabilityy { get; set; }
        [DisplayName("Product ID")]
        [Required(ErrorMessage = "Product ID is required")]
        public Nullable<int> ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
